version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["npm", "run", "db:push"]
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-Career Counselor}
      WATCHPACK_POLLING: "true"
    ports:
      - "3001:3000"   # host:container
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  pgdata:
